### ISSUE TITLE
Utiliser une CI

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#52]
Pour vérifier que vos pushs et vos PRs ne vont pas casser votre app, vous pouvez mettre en place une CI.

Je vous recommande GitHub Actions pour commencer: gratuit et très complet.

https://docs.github.com/en/actions

Un petit exemple:

`./.github/workflows`
```yaml
name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python manage.py test
```
